apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sso
  namespace: sso
  annotations:
    cert-manager.io/cluster-issuer: public-issuer
    kubernetes.io/ingress.class: haproxy
    kubernetes.io/tls-acme: 'true'
    route.openshift.io/termination: reencrypt
    cert-utils-operator.redhat-cop.io/destinationCA-from-secret: private-sso-tls
    cert-utils-operator.redhat-cop.io/certs-from-secret: public-sso-tls
  labels:
    use-dns01-solver: "true"
spec:
  rules:
    - host: sso.$(APPS_DOMAIN)
      http:
        paths:
          - path: /
            backend:
              serviceName: sso
              servicePort: https
  tls:
    - hosts:
        - sso.$(APPS_DOMAIN)
      secretName: public-sso-tls