apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-sso-tls
  namespace: sso
spec:
  secretName: internal-sso-tls
  subject:
    organizations:
    - Open Cluster Management
  usages:
    - server auth
    - client auth
  dnsNames:
    - sso
    - sso.svc
    - sso.svc.cluster.local
    - sso.sso.svc
    - sso.sso.svc.cluster.local
    - sso.apps.keyring.cicd.red-chesterfield.com
  duration: 720h0m0s
  renewBefore: 168h0m0s
  privateKey:
    algorithm: "RSA"
    size: 2048
  issuerRef:
    name: ssi
    kind: ClusterIssuer