apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
- name: dex-config
  files:
    - dex-config.yaml

resources:
  - github-oauth-creds.yaml
  - sso-sa.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  # - route.yaml

bases:
  - dex-client