apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

components:
  - github.com/ocm-sop/apps-domain-tls-cert?ref=main
  
configMapGenerator:
- name: dex-config
  namespace: sso
  files:
    - config.yaml

resources:
  - github-creds.yaml
  - sso-sa.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - dex-client-controller.yaml