apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
- name: dex-config
  namespace: sso
  files:
    - config.yaml

resources:
  - github-creds.yaml
  - sso-sa.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  # - route.yaml