apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
- name: sso-config
  files:
    - config.yaml

resources:
  - namespace.yaml
  - public-tls-secret.yaml
  - public-tls.yaml
  - internal-tls-secret.yaml
  - internal-tls.yaml
  - github-creds.yaml
  - sa.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  # - route.yaml

bases:
  - oauth
  - dex-client