apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: public-sso-tls
  namespace: sso
  labels:
    use-dns01-solver: "true"
spec:
  secretName: sso-tls
  subject:
    organizations:
    - Open Cluster Management
  usages:
    - server auth
    - client auth
  dnsNames:
    - "sso.apps.openshift-cluster-name.base-domain.tld"
  duration: 720h0m0s
  renewBefore: 168h0m0s
  privateKey:
    algorithm: "RSA"
    size: 2048
  issuerRef:
    name: psi
    kind: ClusterIssuer