apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sso-sa
  labels:
    app: sso
rules:
- apiGroups: ["dex.coreos.com"] # API group created by dex
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create"] # To manage its own resources, dex must be able to create customresourcedefinitions
- apiGroups: [""]
  resources: ["configmaps"]
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: [""]
  resources: ["configmaps/status"]
  verbs:
  - get
  - update
  - patch
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - list
  - watch
- apiGroups:
  - dex.betssongroup.com
  resources:
  - albauths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dex.betssongroup.com
  resources:
  - albauths/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dex.betssongroup.com
  resources:
  - clients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dex.betssongroup.com
  resources:
  - clients/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- nonResourceURLs:
  - /metrics
  verbs:
  - get
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sso-sa-rb
  labels:
    app: sso
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sso-sa
subjects:
- kind: ServiceAccount
  name: sso-sa           # Service account assigned to the dex pod, created above
  namespace: sso  # The namespace dex is running in