apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: "sso"

resources:
  - https://raw.githubusercontent.com/BetssonGroup/dex-operator/v0.2.0/contrib/charts/dex-operator/crds/crds.yaml
  - dex-client-deployment.yaml