apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: sso-oauth
  namespace: openshift-config
spec:
  identityProviders:
    - mappingMethod: claim
      name: sso
      openID:
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - preferred_username
            - email
            - name
        clientID: ocp-host-cluster
        clientSecret:
          name: ocp-host-cluster-sso-client-creds
        extraAuthorizeParameters:
          include_granted_scopes: 'true'
        extraScopes:
          - email
          - profile
          - groups
          - 'federated:id'
          - offline_access
        issuer: 'https://sso.apps.keyring.cicd.red-chesterfield.com'
      type: OpenID